// <auto-generated />
using System;
using BestFit.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BestFit.Infrastructure.Migrations
{
    [DbContext(typeof(BestFitDbContext))]
    [Migration("20251202072655_SeedRoles")]
    partial class SeedRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BestFit.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BestFit.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.CustomerMeasurementProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UnitSystem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "ProfileName");

                    b.ToTable("CustomerMeasurementProfiles");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.OrderDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("OrderPrice")
                        .HasColumnType("float");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductMeasurementProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.ProductMeasurementProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnitSystem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductMeasurementProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3c7b2bba-99ab-4768-b124-4abb40a94daa",
                            ConcurrencyStamp = "3c7b2bba-99ab-4768-b124-4abb40a94daa",
                            Name = "Handler",
                            NormalizedName = "HANDLER"
                        },
                        new
                        {
                            Id = "6afa6e31-910f-4963-94ac-d7a23c6d377d",
                            ConcurrencyStamp = "6afa6e31-910f-4963-94ac-d7a23c6d377d",
                            Name = "Shopper",
                            NormalizedName = "SHOPPER"
                        },
                        new
                        {
                            Id = "38c6732b-f36b-4e3a-b8f6-26be2dce3973",
                            ConcurrencyStamp = "38c6732b-f36b-4e3a-b8f6-26be2dce3973",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "cfab018d-40e3-4f0c-af89-00e7cd9f9724",
                            ConcurrencyStamp = "cfab018d-40e3-4f0c-af89-00e7cd9f9724",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BestFit.Domain.Entities.Cart", b =>
                {
                    b.HasOne("BestFit.Domain.Entities.ApplicationUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestFit.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.CustomerMeasurementProfile", b =>
                {
                    b.HasOne("BestFit.Domain.Entities.ApplicationUser", "Customer")
                        .WithMany("CustomerMeasurementProfiles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BestFit.Domain.ValueObjects.ArmAndHandMeasurements", "Arms", b1 =>
                        {
                            b1.Property<Guid>("CustomerMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("BicepCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Arms_BicepCircumference");

                            b1.Property<decimal?>("HandCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Arms_HandCircumference");

                            b1.Property<decimal?>("RingFingerSize")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Arms_RingFingerSize");

                            b1.Property<decimal?>("SleeveLength")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Arms_SleeveLength");

                            b1.Property<decimal?>("WristCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Arms_WristCircumference");

                            b1.HasKey("CustomerMeasurementProfileId");

                            b1.ToTable("CustomerMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerMeasurementProfileId");
                        });

                    b.OwnsOne("BestFit.Domain.ValueObjects.FootMeasurements", "Feet", b1 =>
                        {
                            b1.Property<Guid>("CustomerMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("FootLength")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Feet_FootLength");

                            b1.Property<decimal?>("FootWidth")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Feet_FootWidth");

                            b1.HasKey("CustomerMeasurementProfileId");

                            b1.ToTable("CustomerMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerMeasurementProfileId");
                        });

                    b.OwnsOne("BestFit.Domain.ValueObjects.HeadMeasurements", "Head", b1 =>
                        {
                            b1.Property<Guid>("CustomerMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("HeadCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Head_HeadCircumference");

                            b1.Property<decimal?>("NeckCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Head_NeckCircumference");

                            b1.HasKey("CustomerMeasurementProfileId");

                            b1.ToTable("CustomerMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerMeasurementProfileId");
                        });

                    b.OwnsOne("BestFit.Domain.ValueObjects.LegMeasurements", "Legs", b1 =>
                        {
                            b1.Property<Guid>("CustomerMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("CalfCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Legs_CalfCircumference");

                            b1.Property<decimal?>("Inseam")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Legs_Inseam");

                            b1.Property<decimal?>("Outseam")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Legs_Outseam");

                            b1.Property<decimal?>("ThighCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Legs_ThighCircumference");

                            b1.HasKey("CustomerMeasurementProfileId");

                            b1.ToTable("CustomerMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerMeasurementProfileId");
                        });

                    b.OwnsOne("BestFit.Domain.ValueObjects.LowerBodyMeasurements", "HipsAndWaist", b1 =>
                        {
                            b1.Property<Guid>("CustomerMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("FrontRise")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Lower_FrontRise");

                            b1.Property<decimal?>("HipCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Lower_HipCircumference");

                            b1.Property<decimal?>("TrouserWaist")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Lower_TrouserWaist");

                            b1.HasKey("CustomerMeasurementProfileId");

                            b1.ToTable("CustomerMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerMeasurementProfileId");
                        });

                    b.OwnsOne("BestFit.Domain.ValueObjects.TorsoMeasurements", "Torso", b1 =>
                        {
                            b1.Property<Guid>("CustomerMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("BackLength")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Torso_BackLength");

                            b1.Property<decimal?>("ChestCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Torso_ChestCircumference");

                            b1.Property<decimal?>("NaturalWaist")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Torso_NaturalWaist");

                            b1.Property<decimal?>("ShoulderWidth")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Torso_ShoulderWidth");

                            b1.Property<decimal?>("UnderBustCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Torso_UnderBustCircumference");

                            b1.HasKey("CustomerMeasurementProfileId");

                            b1.ToTable("CustomerMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("CustomerMeasurementProfileId");
                        });

                    b.Navigation("Arms")
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Feet")
                        .IsRequired();

                    b.Navigation("Head")
                        .IsRequired();

                    b.Navigation("HipsAndWaist")
                        .IsRequired();

                    b.Navigation("Legs")
                        .IsRequired();

                    b.Navigation("Torso")
                        .IsRequired();
                });

            modelBuilder.Entity("BestFit.Domain.Entities.OrderDetails", b =>
                {
                    b.HasOne("BestFit.Domain.Entities.OrderProduct", "OrderProduct")
                        .WithMany()
                        .HasForeignKey("OrderProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestFit.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderProduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.OrderProduct", b =>
                {
                    b.HasOne("BestFit.Domain.Entities.ApplicationUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.Product", b =>
                {
                    b.HasOne("BestFit.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("BestFit.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.ProductMeasurementProfile", b =>
                {
                    b.HasOne("BestFit.Domain.Entities.Product", "Product")
                        .WithOne("ProductMeasurementProfile")
                        .HasForeignKey("BestFit.Domain.Entities.ProductMeasurementProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BestFit.Domain.ValueObjects.AccessoryDimensions", "Accessories", b1 =>
                        {
                            b1.Property<Guid>("ProductMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("MaxCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Acc_MaxCircumference");

                            b1.Property<decimal?>("MinCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Acc_MinCircumference");

                            b1.Property<decimal?>("RingInnerCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Acc_RingInnerCircumference");

                            b1.Property<decimal?>("TotalLength")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Acc_TotalLength");

                            b1.HasKey("ProductMeasurementProfileId");

                            b1.ToTable("ProductMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("ProductMeasurementProfileId");
                        });

                    b.OwnsOne("BestFit.Domain.ValueObjects.BottomWearDimensions", "Bottoms", b1 =>
                        {
                            b1.Property<Guid>("ProductMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("FrontRise")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Bottom_FrontRise");

                            b1.Property<decimal?>("HipWidthFlat")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Bottom_HipWidthFlat");

                            b1.Property<decimal?>("Inseam")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Bottom_Inseam");

                            b1.Property<decimal?>("LegOpeningWidth")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Bottom_LegOpeningWidth");

                            b1.Property<decimal?>("ThighWidthFlat")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Bottom_ThighWidthFlat");

                            b1.Property<decimal?>("WaistWidthFlat")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Bottom_WaistWidthFlat");

                            b1.HasKey("ProductMeasurementProfileId");

                            b1.ToTable("ProductMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("ProductMeasurementProfileId");
                        });

                    b.OwnsOne("BestFit.Domain.ValueObjects.FabricProperties", "MaterialInfo", b1 =>
                        {
                            b1.Property<Guid>("ProductMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DesignedFit")
                                .HasColumnType("int")
                                .HasColumnName("Fabric_DesignedFit");

                            b1.Property<int>("Elasticity")
                                .HasColumnType("int")
                                .HasColumnName("Fabric_Elasticity");

                            b1.HasKey("ProductMeasurementProfileId");

                            b1.ToTable("ProductMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("ProductMeasurementProfileId");
                        });

                    b.OwnsOne("BestFit.Domain.ValueObjects.FootWearDimensions", "Shoes", b1 =>
                        {
                            b1.Property<Guid>("ProductMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("BootOpeningCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Shoe_BootOpeningCircumference");

                            b1.Property<decimal?>("BootShaftHeight")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Shoe_BootShaftHeight");

                            b1.Property<decimal?>("HeelHeight")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Shoe_HeelHeight");

                            b1.Property<decimal?>("InnerSoleLength")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Shoe_InnerSoleLength");

                            b1.Property<decimal?>("InnerSoleWidth")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Shoe_InnerSoleWidth");

                            b1.HasKey("ProductMeasurementProfileId");

                            b1.ToTable("ProductMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("ProductMeasurementProfileId");
                        });

                    b.OwnsOne("BestFit.Domain.ValueObjects.HeadWearDimensions", "HeadWear", b1 =>
                        {
                            b1.Property<Guid>("ProductMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("BrimWidth")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Head_BrimWidth");

                            b1.Property<decimal?>("CrownHeight")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Head_CrownHeight");

                            b1.Property<decimal?>("InnerCircumference")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Head_InnerCircumference");

                            b1.HasKey("ProductMeasurementProfileId");

                            b1.ToTable("ProductMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("ProductMeasurementProfileId");
                        });

                    b.OwnsOne("BestFit.Domain.ValueObjects.TopWearDimensions", "Tops", b1 =>
                        {
                            b1.Property<Guid>("ProductMeasurementProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("ChestWidthFlat")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Top_ChestWidthFlat");

                            b1.Property<decimal?>("HemWidthFlat")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Top_HemWidthFlat");

                            b1.Property<decimal?>("ShoulderWidth")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Top_ShoulderWidth");

                            b1.Property<decimal?>("SleeveLength")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Top_SleeveLength");

                            b1.Property<decimal?>("TotalLength")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Top_TotalLength");

                            b1.Property<decimal?>("WaistWidthFlat")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Top_WaistWidthFlat");

                            b1.HasKey("ProductMeasurementProfileId");

                            b1.ToTable("ProductMeasurementProfiles");

                            b1.WithOwner()
                                .HasForeignKey("ProductMeasurementProfileId");
                        });

                    b.Navigation("Accessories")
                        .IsRequired();

                    b.Navigation("Bottoms")
                        .IsRequired();

                    b.Navigation("HeadWear")
                        .IsRequired();

                    b.Navigation("MaterialInfo")
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shoes")
                        .IsRequired();

                    b.Navigation("Tops")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BestFit.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BestFit.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestFit.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BestFit.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BestFit.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("CustomerMeasurementProfiles");
                });

            modelBuilder.Entity("BestFit.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductMeasurementProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
