<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-BestFit.Web-969f2804-d54f-490a-8ebc-95e0cd717035</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\Home\About.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Home\About.cshtml" />
    <None Include="wwwroot\assets\images\demo\banner-1.jpg" />
    <None Include="wwwroot\assets\images\demo\card-amex.png" />
    <None Include="wwwroot\assets\images\demo\card-diners-club.png" />
    <None Include="wwwroot\assets\images\demo\card-discover.png" />
    <None Include="wwwroot\assets\images\demo\card-jcb.png" />
    <None Include="wwwroot\assets\images\demo\card-mastercard.png" />
    <None Include="wwwroot\assets\images\demo\card-visa.png" />
    <None Include="wwwroot\assets\images\demo\demo-desktop.jpg" />
    <None Include="wwwroot\assets\images\demo\demo-mobile.jpg" />
    <None Include="wwwroot\assets\images\demo\fashion-1.jpg" />
    <None Include="wwwroot\assets\images\demo\fashion-2.jpg" />
    <None Include="wwwroot\assets\images\demo\fashion-3.jpg" />
    <None Include="wwwroot\assets\images\demo\fashion-4.jpg" />
    <None Include="wwwroot\assets\images\demo\placeholder-2.jpg" />
    <None Include="wwwroot\assets\images\demo\placeholder-3.jpg" />
    <None Include="wwwroot\assets\images\demo\placeholder-4.jpg" />
    <None Include="wwwroot\assets\images\demo\placeholder-wide.jpg" />
    <None Include="wwwroot\assets\images\demo\placeholder.jpg" />
    <None Include="wwwroot\assets\images\demo\product-1.png" />
    <None Include="wwwroot\assets\images\demo\product-10.png" />
    <None Include="wwwroot\assets\images\demo\product-11.png" />
    <None Include="wwwroot\assets\images\demo\product-12.png" />
    <None Include="wwwroot\assets\images\demo\product-1b.png" />
    <None Include="wwwroot\assets\images\demo\product-1c.png" />
    <None Include="wwwroot\assets\images\demo\product-2.png" />
    <None Include="wwwroot\assets\images\demo\product-3.png" />
    <None Include="wwwroot\assets\images\demo\product-4.png" />
    <None Include="wwwroot\assets\images\demo\product-5.png" />
    <None Include="wwwroot\assets\images\demo\product-6.png" />
    <None Include="wwwroot\assets\images\demo\product-7.png" />
    <None Include="wwwroot\assets\images\demo\product-8.png" />
    <None Include="wwwroot\assets\images\demo\product-9.png" />
    <None Include="wwwroot\assets\images\demo\user-1.jpg" />
    <None Include="wwwroot\assets\images\demo\user-10.jpg" />
    <None Include="wwwroot\assets\images\demo\user-2.jpg" />
    <None Include="wwwroot\assets\images\demo\user-3.jpg" />
    <None Include="wwwroot\assets\images\demo\user-4.jpg" />
    <None Include="wwwroot\assets\images\demo\user-5.jpg" />
    <None Include="wwwroot\assets\images\demo\user-6.jpg" />
    <None Include="wwwroot\assets\images\demo\user-7.jpg" />
    <None Include="wwwroot\assets\images\demo\user-8.jpg" />
    <None Include="wwwroot\assets\images\demo\user-9.jpg" />
    <None Include="wwwroot\assets\images\general\1.jpg" />
    <None Include="wwwroot\assets\images\general\2.jpg" />
    <None Include="wwwroot\assets\images\general\3.jpg" />
    <None Include="wwwroot\assets\images\general\4.jpg" />
    <None Include="wwwroot\assets\images\general\5.jpg" />
    <None Include="wwwroot\assets\images\general\6.jpg" />
    <None Include="wwwroot\assets\images\general\7.jpg" />
    <None Include="wwwroot\assets\images\general\8.jpg" />
    <None Include="wwwroot\assets\images\general\9.jpg" />
    <None Include="wwwroot\assets\images\general\c1.jpg" />
    <None Include="wwwroot\assets\images\general\x1.jpg" />
    <None Include="wwwroot\assets\images\general\x2.jpg" />
    <None Include="wwwroot\assets\images\general\x3.jpg" />
    <None Include="wwwroot\assets\images\general\x4.jpg" />
    <None Include="wwwroot\assets\images\general\x5.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c1.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c10.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c11.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c12.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c13.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c14.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c2.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c3.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c4.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c5.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c6.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c7.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c8.jpg" />
    <None Include="wwwroot\assets\images\layouts\components\c9.jpg" />
    <None Include="wwwroot\assets\images\layouts\layout-agency.png" />
    <None Include="wwwroot\assets\images\layouts\layout-architecture.png" />
    <None Include="wwwroot\assets\images\layouts\layout-clothing.png" />
    <None Include="wwwroot\assets\images\layouts\layout-corporate.png" />
    <None Include="wwwroot\assets\images\layouts\layout-fashion.png" />
    <None Include="wwwroot\assets\images\layouts\layout-furniture.png" />
    <None Include="wwwroot\assets\images\layouts\layout-hotel.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\1.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\10.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\11.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\12.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\13.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\14.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\15.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\16.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\17.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\18.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\19.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\2.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\20.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\21.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\3.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\4.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\5.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\6.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\7.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\8.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\9.png" />
    <None Include="wwwroot\assets\images\layouts\mobile\mobile.png" />
    <None Include="wwwroot\assets\images\layouts\page-about.png" />
    <None Include="wwwroot\assets\images\layouts\page-blog-2.png" />
    <None Include="wwwroot\assets\images\layouts\page-blog.png" />
    <None Include="wwwroot\assets\images\layouts\page-checkout-delivery.png" />
    <None Include="wwwroot\assets\images\layouts\page-checkout-login.png" />
    <None Include="wwwroot\assets\images\layouts\page-checkout-payment.png" />
    <None Include="wwwroot\assets\images\layouts\page-checkout-receipt.png" />
    <None Include="wwwroot\assets\images\layouts\page-checkout.png" />
    <None Include="wwwroot\assets\images\layouts\page-portfolio.png" />
    <None Include="wwwroot\assets\images\layouts\page-product-preview-1.png" />
    <None Include="wwwroot\assets\images\layouts\page-product-preview-2.png" />
    <None Include="wwwroot\assets\images\layouts\page-product-preview-3.png" />
    <None Include="wwwroot\assets\images\layouts\page-product.png" />
    <None Include="wwwroot\assets\images\layouts\page-products-grid-flat.png" />
    <None Include="wwwroot\assets\images\layouts\page-products-grid.png" />
    <None Include="wwwroot\assets\images\layouts\page-products-list-flat.png" />
    <None Include="wwwroot\assets\images\layouts\page-products-list.png" />
    <None Include="wwwroot\assets\images\layouts\page-profile-notifications.png" />
    <None Include="wwwroot\assets\images\layouts\page-profile-orders.png" />
    <None Include="wwwroot\assets\images\layouts\page-profile-payment.png" />
    <None Include="wwwroot\assets\images\layouts\page-profile-whishlist.png" />
    <None Include="wwwroot\assets\images\layouts\page-profile.png" />
    <None Include="wwwroot\assets\images\layouts\page-services.png" />
    <None Include="wwwroot\assets\images\layouts\page-team.png" />
    <None Include="wwwroot\assets\images\layouts\product-list.png" />
    <None Include="wwwroot\assets\svg\mobile-usage.svg" />
    <None Include="wwwroot\assets\svg\reveal-logo.svg" />
    <None Include="wwwroot\assets\svg\reveal-symbol.svg" />
    <None Include="wwwroot\css\fonts\fontawesome-webfont.eot" />
    <None Include="wwwroot\css\fonts\fontawesome-webfont.svg" />
    <None Include="wwwroot\css\fonts\fontawesome-webfont.ttf" />
    <None Include="wwwroot\css\fonts\fontawesome-webfont.woff" />
    <None Include="wwwroot\css\fonts\fontawesome-webfont.woff2" />
    <None Include="wwwroot\css\fonts\FontAwesome.otf" />
    <None Include="wwwroot\css\fonts\linearIcons.eot" />
    <None Include="wwwroot\css\fonts\linearIcons.svg" />
    <None Include="wwwroot\css\fonts\linearIcons.ttf" />
    <None Include="wwwroot\css\fonts\linearIcons.woff" />
    <None Include="wwwroot\css\fonts\linearIcons.woff2" />
    <None Include="wwwroot\css\style.css" />
    <None Include="wwwroot\css\style.css.map" />
    <None Include="wwwroot\css\vendor\animate.css" />
    <None Include="wwwroot\css\vendor\font-awesome.css" />
    <None Include="wwwroot\css\vendor\jquery.lavalamp.css" />
    <None Include="wwwroot\css\vendor\linear-icons.css" />
    <None Include="wwwroot\css\vendor\owl.carousel.css" />
    <None Include="wwwroot\js\core.js" />
    <None Include="wwwroot\js\custom.js" />
    <None Include="wwwroot\js\main.js" />
    <None Include="wwwroot\js\vendor\bootstrap.bundle.js" />
    <None Include="wwwroot\js\vendor\bootstrap.bundle.js.map" />
    <None Include="wwwroot\js\vendor\bootstrap.bundle.min.js" />
    <None Include="wwwroot\js\vendor\in-view.min.js" />
    <None Include="wwwroot\js\vendor\isotope.pkgd.js" />
    <None Include="wwwroot\js\vendor\isotope.pkgd.min.js" />
    <None Include="wwwroot\js\vendor\jquery.lavalamp.js" />
    <None Include="wwwroot\js\vendor\jquery.lavalamp.min.js" />
    <None Include="wwwroot\js\vendor\jquery.min.js" />
    <None Include="wwwroot\js\vendor\owl.carousel.js" />
    <None Include="wwwroot\js\vendor\owl.carousel.min.js" />
    <None Include="wwwroot\js\vendor\rellax.js" />
    <None Include="wwwroot\js\vendor\rellax.min.js" />
    <None Include="wwwroot\js\vendor\tabzy.js" />
    <None Include="wwwroot\js\vendor\tabzy.min.js" />
    <None Include="wwwroot\js\vendor\wow.js" />
    <None Include="wwwroot\js\vendor\wow.min.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BestFit.Domain\BestFit.Domain.csproj" />
  </ItemGroup>

</Project>
